// Step 3: turn the exported stylesheets (mowix-export/css) into src/styles/mowix/.
// Run from the project root after export-mowix.mjs: node mowix-export/build-css.mjs
import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, "mowix-export", "css");
const OUT_DIR = path.join(ROOT, "src", "styles", "mowix");

// Output files in cascade order; each lists its exported sources (by number prefix) in load order.
const GROUPS = [
  { file: "01-theme.css", title: "Hello Elementor theme (reset + base)", sources: ["05", "06"] },
  { file: "02-elementor-frontend.css", title: "Elementor frontend core", sources: ["08"] },
  { file: "03-kit.css", title: "Elementor kit 3 — global colors, typography, buttons", sources: ["09"] },
  {
    file: "04-widgets.css",
    title: "Elementor / Elementor Pro widget, animation and Swiper styles",
    sources: ["10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"],
  },
  { file: "05-page-home.css", title: "Home page (Elementor post 971)", sources: ["32"] },
  { file: "06-header.css", title: "Header template (Elementor post 335)", sources: ["33"] },
  { file: "07-footer.css", title: "Footer template (Elementor post 1002)", sources: ["34"] },
  { file: "08-blog-loop.css", title: "Blog loop item (Elementor post 1065) + post info widget", sources: ["36", "37"] },
];

// Not carried over (all verified unused by the home page):
// 01 img auto-sizes, 02 emoji, 03 WP block global styles, 04 template-kit plugin,
// 07 Hello default header/footer (.site-header etc. not in markup),
// 35 Elementor lazy-load rule (hides backgrounds until Elementor JS adds .e-lazyloaded).
const DROPPED = ["01", "02", "03", "04", "07", "35"];

function clean(css) {
  return css
    .replace(/@charset\s+["'][^"']*["'];?/gi, "")
    .replace(/\/\*#\s*source(Mapping)?URL=[^*]*\*\//g, "")
    // Hello theme declares these but never uses them; browsers ignore them and the minifier warns.
    .replace(/@custom-media\s+[^;]+;/g, "")
    // Montserrat is self-hosted by next/font, which exposes it as --font-montserrat.
    .replace(/(["'])Montserrat\1/g, "var(--font-montserrat)")
    .trim();
}

async function main() {
  const files = (await fs.readdir(SRC_DIR)).filter((f) => f.endsWith(".css"));
  const byPrefix = new Map(files.map((f) => [f.slice(0, 2), f]));

  const used = new Set([...DROPPED, ...GROUPS.flatMap((g) => g.sources)]);
  const unassigned = [...byPrefix.keys()].filter((k) => !used.has(k));
  if (unassigned.length) throw new Error(`Exported CSS not assigned to a group: ${unassigned.join(", ")}`);

  await fs.mkdir(OUT_DIR, { recursive: true });
  for (const group of GROUPS) {
    const parts = [];
    for (const prefix of group.sources) {
      const name = byPrefix.get(prefix);
      if (!name) throw new Error(`Missing exported CSS ${prefix}`);
      const css = clean(await fs.readFile(path.join(SRC_DIR, name), "utf8"));
      parts.push(`/* ---- source: mowix-export/css/${name} ---- */\n${css}`);
    }
    const out = `/* ${group.title} — generated by mowix-export/build-css.mjs, do not edit by hand */\n\n${parts.join("\n\n")}\n`;
    await fs.writeFile(path.join(OUT_DIR, group.file), out);
    console.log(`${group.file.padEnd(28)} ${(out.length / 1024).toFixed(1).padStart(6)} KB  <- ${group.sources.join(",")}`);
  }

  const index = [
    "/* Mowix home page styles, in the original WordPress load order.",
    " * Imported into the `mowix` cascade layer from src/app/globals.css. */",
    ...GROUPS.map((g) => `@import "./${g.file}";`),
    "",
  ].join("\n");
  await fs.writeFile(path.join(OUT_DIR, "index.css"), index);
  console.log("index.css written");
}

main().catch((err) => { console.error(err); process.exit(1); });
